version: "3"
services:
  mysql:
    container_name: counter_be_db
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'counter_sync'
      MYSQL_ROOT_PASSWORD: '1qaz2wsx'
    volumes:
      - ./storage/docker/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    restart: on-failure
  app:
    container_name: counter_be_dev
    image: node:10.16.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
    command: yarn run dev
  
    
