version: "3"
services:
  app:
    image: node:10.16.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
    command: yarn run dev